# Generated by Django 3.2.8 on 2021-10-22 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100, null=True, verbose_name='Nombre del Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, verbose_name='Nombre de la Acción')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=70, verbose_name='Nombre del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallazgo', models.CharField(max_length=30, verbose_name='Nombre Hallazgo')),
                ('estado_Avance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_avance', verbose_name='Nombre del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True, verbose_name='Nombre del Grupo General')),
                ('descripcion', models.TextField(max_length=200, null=True, verbose_name='Descripción')),
                ('ente_control', models.CharField(max_length=200, null=True, verbose_name='Ente de Control')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_indi', models.CharField(choices=[('Indicador de Producto', 'Indicador de Producto'), ('Indicador de Economía', 'Indicador de Economía'), ('Indicador de Eficacia', 'Indicador de Eficacia'), ('Indicador de Eficiencia', 'Indicador de Eficiencia'), ('Indicador de Proceso', 'Indicador de Proceso'), ('Indicador de Calidad', 'Indicador de Calidad'), ('Indicador de Resultado', 'Indicador de Resultado'), ('Indicador de Insumo', 'Indicador de Insumo')], default='Indicador de Eficiencia', max_length=30)),
                ('metrica_indicador', models.CharField(choices=[('metrica', 'Métrica'), ('indicador', 'Indicador')], default='indicador', max_length=9)),
                ('nombre', models.CharField(max_length=60, null=True, verbose_name='Nombre del Indicador')),
                ('nombre_numerador', models.CharField(max_length=80, null=True, verbose_name='Nombre del Numerador')),
                ('nombre_denominador', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre del Denominador')),
                ('estandar', models.FloatField(default=1, null=True, verbose_name='Estandar del Indicador')),
                ('objetivo', models.TextField(null=True, verbose_name='Objetivo')),
                ('justificacion', models.TextField(null=True, verbose_name='Justificación')),
                ('dominio', models.CharField(max_length=100, null=True, verbose_name='Dominio')),
                ('tendencia_ascendente', models.CharField(choices=[('Ascendente', 'Ascendente'), ('Descendente', 'Descendente')], default='Ascendente', max_length=11)),
                ('periodicidad', models.CharField(choices=[('Diaria', 'Diaria'), ('Mensual', 'Mensual')], default='Mensual', max_length=7)),
                ('cantidad_periodicidad', models.IntegerField(default=1, verbose_name='Cantidad Periodicidad')),
                ('fuente_num', models.CharField(max_length=30, null=True, verbose_name='Fuente Númerador')),
                ('fuente_den', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuente Denominador')),
                ('factor', models.FloatField(default=1, verbose_name='Factor')),
                ('formula', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formula')),
                ('vigil_control', models.CharField(max_length=150, null=True, verbose_name='Vigiancia y Control')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.cargo', verbose_name='Responsable')),
                ('grupo_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.grupo_general', verbose_name='Grupo General')),
            ],
        ),
        migrations.CreateModel(
            name='Lenar_Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerador', models.FloatField(null=True, verbose_name='Valor Numerador')),
                ('valor_denominador', models.FloatField(default=1, null=True, verbose_name='Valor Denominador')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Periodo')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Periodo')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Registro del Indicador')),
                ('resultado', models.FloatField(blank=True, default=0, verbose_name='Resultado')),
                ('analisis', models.TextField(null=True, verbose_name='Analisis')),
                ('observacion', models.TextField(null=True, verbose_name='Analisis')),
                ('grupo_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.grupo_general', verbose_name='Grupo General')),
                ('indicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.indicador', verbose_name='Nombre del Indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_ref', models.CharField(max_length=70, null=True, verbose_name='Nivel de Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_norma', models.CharField(max_length=100, null=True, verbose_name='Nombre de la Norma')),
                ('descripcion_norma', models.TextField(null=True, verbose_name='Descripción Norma')),
                ('tipo_documento', models.CharField(choices=[('Ley', 'Ley'), ('Decreto', 'Decreto'), ('Resolución', 'Resolución'), ('Circular', 'Circular'), ('Acuerdo', 'Acuerdo')], default='Ley', max_length=12, verbose_name='Tipo de Documento')),
                ('num_norma', models.CharField(max_length=10, null=True, verbose_name='Número Norma')),
                ('fecha_emision', models.DateField(null=True, verbose_name='Fecha Emision')),
                ('emitido', models.CharField(max_length=100, null=True, verbose_name='Emitido Por')),
                ('estado', models.CharField(max_length=100, null=True, verbose_name='Estado')),
                ('dir_url', models.CharField(max_length=200, null=True, verbose_name='Direccion URL')),
                ('obs', models.TextField(null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidad_Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oport_ejec', models.CharField(max_length=70, verbose_name='Oportunidad de Ejecución')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Mejoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField(verbose_name='¿QUE?')),
                ('para_que', models.TextField(verbose_name='¿PARA QUE?')),
                ('quien', models.TextField(verbose_name='¿QUIEN?')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termin', models.DateField(verbose_name='Fecha de Terminación')),
                ('donde', models.TextField(verbose_name='¿DONDE?')),
                ('como', models.TextField(verbose_name='¿COMO?')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('cuento_costara', models.FloatField(null=True, verbose_name='¿Cuanto Costará ?')),
                ('lenar_Indicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.lenar_indicador', verbose_name='Indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Porcentaje_Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc_avance', models.CharField(max_length=20, verbose_name='Porcentaje de Avance')),
                ('estado_Avance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_avance', verbose_name='Nombre del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_proc', models.CharField(max_length=100, null=True, verbose_name='Tipo de Proceso')),
                ('descrip_tipo_proc', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True, verbose_name='Nombre del Tipo de Reporte')),
                ('descripcion', models.TextField(max_length=200, null=True, verbose_name='Descripción del Tipo de Reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid_medida', models.CharField(max_length=20, null=True, verbose_name='Unidad de Medida')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Master', 'Master'), ('Digitador', 'Digitador'), ('Lector', 'Lector')], default='Lector', max_length=50, null=True, verbose_name='Rol')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.cargo', verbose_name='Cargo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True, verbose_name='Nombre del Sub-Grupo')),
                ('descripcion', models.TextField(max_length=200, null=True, verbose_name='Descripción del Sub-Grupo')),
                ('grupo_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.grupo_general', verbose_name='Grupo General')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Eficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponsable', models.CharField(max_length=70, verbose_name='Responsable')),
                ('soportes_evidencias', models.TextField(verbose_name='Soportes o Evidencias')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de Evaluacion o Cierre')),
                ('observacion', models.TextField(verbose_name='Observaciones')),
                ('estado_Accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_accion', verbose_name='Estado de la Acción')),
                ('estado_Avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_avance', verbose_name='Estado de Avance')),
                ('estado_Hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_hallazgo', verbose_name='Estado del hallazgo')),
                ('oportunidad_Ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.oportunidad_ejecucion', verbose_name='Oportunidad de Evacuación')),
                ('plan_Mejoramiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.plan_mejoramiento', verbose_name='Plan de Mejoramiento')),
                ('porcentaje_Avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.porcentaje_avance', verbose_name='Porcentaje de Avance')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(max_length=100, null=True, verbose_name='Nombre del Proceso')),
                ('objetivo', models.TextField(null=True, verbose_name='Objetivo del Proceso')),
                ('alcance', models.TextField(null=True, verbose_name='Alcance del Proceso')),
                ('codigo', models.CharField(max_length=20, null=True, verbose_name='Código del Proceso')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.cargo', verbose_name='Responsable')),
                ('norma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.norma', verbose_name='Norma')),
                ('tipo_Proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.tipo_proc', verbose_name='Tipo de Proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro_Segui_Eficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_Avance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_avance', verbose_name='Nombre del Estado')),
                ('estado_Hallazgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_hallazgo', verbose_name='Nombre Hallazgo')),
                ('estado_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_accion', verbose_name='Estado de la Acción')),
                ('porcentaje_avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.porcentaje_avance', verbose_name='Porcentaje de Avance')),
            ],
        ),
        migrations.AddField(
            model_name='lenar_indicador',
            name='sub_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.sub_grupo', verbose_name='Sub-Grupo'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nivel_Referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.nivel_referencia', verbose_name='Nivel de Referencia'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.proceso', verbose_name='Nombre del Proceso'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='sub_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.sub_grupo', verbose_name='Sub-Grupo'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='unidad_Medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.unidad_medida', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='grupo_general',
            name='tipo_reporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.tipo_reporte', verbose_name='Tipo de Reporte'),
        ),
        migrations.AddField(
            model_name='estado_accion',
            name='estado_Avance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.estado_avance', verbose_name='Nombre del Estado'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_actividad', models.TextField(null=True, verbose_name='Actividad')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.cargo', verbose_name='Responsable')),
                ('proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.proceso', verbose_name='Nombre del Proceso')),
            ],
        ),
    ]
