# Generated by Django 3.2.8 on 2021-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Diaria', 'Diaria')], default='Mensual', max_length=7),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tendencia_ascendente',
            field=models.CharField(choices=[('Descendente', 'Descendente'), ('Ascendente', 'Ascendente')], default='Ascendente', max_length=11),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipo_indi',
            field=models.CharField(choices=[('Indicador de Eficacia', 'Indicador de Eficacia'), ('Indicador de Proceso', 'Indicador de Proceso'), ('Indicador de Insumo', 'Indicador de Insumo'), ('Indicador de Economía', 'Indicador de Economía'), ('Indicador de Eficiencia', 'Indicador de Eficiencia'), ('Indicador de Producto', 'Indicador de Producto'), ('Indicador de Resultado', 'Indicador de Resultado'), ('Indicador de Calidad', 'Indicador de Calidad')], default='Indicador de Eficiencia', max_length=30),
        ),
    ]
