# Generated by Django 3.2.8 on 2021-10-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del Driver')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='ParentCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='Código Centro de Costo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre Centro de Costo')),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(choices=[('Cedula', 'Cedula'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='Cedula', max_length=15, verbose_name='Tipo Identificación')),
                ('number_id', models.CharField(max_length=15, null=True, verbose_name='Numero de Identificación')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('direction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('telefon', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre Servicio')),
                ('fixedVariable', models.CharField(choices=[('Fijo', 'Fijo'), ('Variable', 'Variable')], default='Fijo', max_length=8, verbose_name='Fijo o Variable')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Costo.driver', verbose_name='Driver de Distribución')),
                ('third', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Costo.third', verbose_name='Tercero')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='Código Centro de Costo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre Centro de Costo')),
                ('parentCostCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Costo.parentcostcenter', verbose_name='Centro de Costo Hijo')),
            ],
        ),
        migrations.CreateModel(
            name='Causation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor a causar')),
                ('account', models.CharField(max_length=20, null=True, verbose_name='Cuenta Contable')),
                ('third', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Costo.third', verbose_name='Grupo General')),
            ],
        ),
    ]
